service: hello

provider:
 name: aws
 runtime: nodejs8.10 
 stage: dev
 region: us-east-2
 iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:us-east-2:247444878684:table/test"

functions:
 app:
  handler: app.helloWorld
  events: 
  - http: 
     path: hello-world
     method: GET
     cors: true
 viewAll:
  handler: app.viewAll
  events:
  - http:
     path: view
     method: GET
     cors: true     